apiVersion: batch/v1
kind: CronJob
metadata:
  name: api2bucket
spec:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: c
            image: group8se4ai/nextbike-prediction:api2bucket
            imagePullPolicy: Always
            env:
            - name: MINIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: token
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: password
          imagePullSecrets:
          - name: regcred
          restartPolicy: Never
