version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - timescale-data:/var/lib/postgresql/data
      - ./setup/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
volumes:
  timescale-data:
    driver: local