apiVersion: v2
name: bike-prediction
description: A Helm chart for Kubernetes

dependencies:
  - name: timescaledb-single
    version: "0.13.1"
    repository: https://charts.timescale.com
    condition: timescaledb-single.enabled
  - name: grafana
    version: "6.32.6"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: initdb
    version: "0.1.0"
    repository: "file://charts/initdb"
    condition: initdb.enabled
  - name: datacollector
    version: "0.1.0"
    repository: "file://charts/datacollector"
    condition: datacollector.enabled
  - name: fastapi
    version: "0.1.0"
    repository: "file://charts/fastapi"
    condition: fastapi.enabled
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"
    condition: frontend.enabled
  - name: mockup
    version: "0.1.0"
    repository: "file://charts/mockup"
    condition: mockup.enabled
  - name: transform-raw-nextbike-data
    version: "0.1.0"
    repository: "file://charts/transform-raw-nextbike-data"
    condition: transform-raw-nextbike-data.enabled



# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
