global:

  defaultContainerName: c

  timescaledb:
    host: timescaledb
    port: 5432
    credentials:
      name: database-credentials
      databaseKey: DB_NAME
      userKey: DB_USER
      passwordKey: DB_PASSWORD

  minio:
    credentials:
      name: minio-credentials
      tokenKey: token
      passwordKey: password

  containerRegistry:
    name: group8se4ai/
    credentials:
      name: registry-credentials

  grafana:
    credentials:
      user: admin
      password: admin


# === Dependecies ===

initdb:
  enabled: true

datacollector: 
  enabled: true
  # when in debug mode, connection to bucket store is established but data not actually written
  debug: true

timescaledb-single:
  enabled: true
  
  # this is important to set here because it will be used for naming the service
  # by which the db is accessible from within the cluster
  clusterName: timescaledb

  replicaCount: 3
  persistentVolumes:
    data:
      size: 10Gi

  # secret setting patroni password for initializing database;
  # those passwords are: admin, superuser, replica
  # for now all of them are set to the same password specified for the database default user (see ./templates/patroni-credentials.yaml)
  secrets:
    credentialsSecretName: patroni-credentials

grafana:
  enabled: true
  # disable role-based-access-control
  rbac:
    create: false
    pspEnabled: false
    useExistingRole: grafana-clusterrole

  # Use an existing secret for the admin user.
  admin:
    existingSecret: grafana-credentials
    userKey: user
    passwordKey: password

  # install additional plugins
  plugins: []

  # enable ingress to access dashboards from outside the cluster
  ingress:
    # deactivate in minikube otherwise no service we be set up for easy debugging
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /grafana/?(.*)
    pathType: Prefix
    hosts:
      - t8.se4ai.sws.informatik.uni-leipzig.de

  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana
