apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: {{ .Values.global.containerRegistry.name }}{{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          env:
          - name: DB_HOST
            value: {{ .Values.global.timescaledb.host | quote}}
          - name: DB_PORT
            value: {{ .Values.global.timescaledb.port | quote}}
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.timescaledb.credentials.name }}
                key: {{ .Values.global.timescaledb.credentials.databaseKey | quote }} 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.timescaledb.credentials.name }}
                key: {{ .Values.global.timescaledb.credentials.userKey | quote }} 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.timescaledb.credentials.name }}
                key: {{ .Values.global.timescaledb.credentials.passwordKey | quote }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
      imagePullSecrets:
        - name: {{ .Values.global.containerRegistry.credentials.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
