apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
      - name: c
        image: group8se4ai/nextbike-prediction:dbinit
        env:
        - name: DB_HOST
          value: "timescaledb"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password

      restartPolicy: Never
      imagePullSecrets:
        - name: regcred

  backoffLimit: 4
