apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.timescaledb.credentials.name }}
data:
  {{ .Values.global.timescaledb.credentials.databaseKey }}: {{ .Values.initdb.credentials.database | b64enc | quote }}
  {{ .Values.global.timescaledb.credentials.userKey }}:  {{ .Values.initdb.credentials.user | b64enc | quote }}
  {{ .Values.global.timescaledb.credentials.passwordKey }}:  {{ .Values.initdb.credentials.password | b64enc | quote }}