apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.timescaledb.credentials.name }}
data:
  {{ .Values.global.timescaledb.credentials.databaseKey }}: {{ .Values.global.timescaledb.database | b64enc | quote }}
  {{ .Values.global.timescaledb.credentials.userKey }}:  {{ .Values.global.timescaledb.user | b64enc | quote }}
  {{ .Values.global.timescaledb.credentials.passwordKey }}:  {{ .Values.global.timescaledb.password | b64enc | quote }}
  {{ .Values.global.timescaledb.credentials.userKey }}:  {{ .Values.global.timescaledb.user | b64enc | quote }}