apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret }}
data:
  {{ .Values.grafana.admin.userKey }}: {{ .Values.global.grafana.credentials.user | b64enc | quote }}
  {{ .Values.grafana.admin.passwordKey }}: {{ .Values.global.grafana.credentials.password | b64enc | quote }}
