apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.minio.credentials.name }}
data:
  {{ .Values.global.minio.credentials.tokenKey }}: {{ .Values.global.minio.token | b64enc | quote }}
  {{ .Values.global.minio.credentials.passwordKey }}: {{ .Values.global.minio.password | b64enc | quote }}
