apiVersion: v1
kind: Secret
metadata:
  # complicated syntax with index user here because timescaledb-singe has dash in name: see https://github.com/helm/helm/issues/2192#issuecomment-293739257
  name: {{ index .Values "timescaledb-single" "secrets" "credentialsSecretName" }} 
data:
  PATRONI_SUPERUSER_PASSWORD: {{ .Values.global.timescaledb.password | b64enc | quote }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.global.timescaledb.password | b64enc | quote }}
  PATRONI_admin_PASSWORD: {{ .Values.global.timescaledb.password | b64enc | quote }}