apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.containerRegistry.credentials.name }}
data:
  .dockerconfigjson: {{ .Values.containerRegistry.dockerconfig }}
type: kubernetes.io/dockerconfigjson